baseURL = "http://www.wesleyreisz.com/getting_started_with_k8s"
languageCode = "en-us"
title = "Getting Started with Containerization and Kubernetes"
enableGitInfo = true
description = "Workshop on k8s"
publishDir = "docs"

[[menu.main]]
name = "Home"
url = "/"
weight = 1